name: macOS

on:
  pull_request:
  push:
    branches:
      - dev
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-12:
    name: macos-12
    runs-on: macos-12
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: go test
      - name: "Run macOS smoke tests"
        run: make smoketest-macos

  macos-13:
    name: macos-13
    runs-on: macos-13
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: go test
      - name: "Run macOS smoke tests"
        run: make smoketest-macos
  
  macos-14:
    name: macos-14
    runs-on: macos-14
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: go test
      - name: "Run macOS smoke tests"
        run: make smoketest-macos
